version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (*os.File).Close
        - (io.Closer).Close
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
    revive:
      rules:
        - name: exported
          disabled: true
    staticcheck:
        checks: ["all", "-SA1019", "-ST1000"]

formatters:
  enable:
    - gofmt
    - goimports
